import java.util.ArrayList;
import java.util.List;
import org.knowm.xchart.*;
import org.knowm.xchart.style.Styler;
import org.knowm.xchart.style.colors.XChartSeriesColors;
import org.knowm.xchart.style.markers.SeriesMarkers;

public class ProfitLossDashboard {
    private List<Product> products;

    public ProfitLossDashboard(List<Product> products) {
        this.products = products;
    }

    public void generateReport() {
        double totalRevenue = 0;
        double totalCost = 0;
        double totalProfit = 0;

        // Initialize chart data
        List<String> productNames = new ArrayList<>();
        List<Double> revenues = new ArrayList<>();
        List<Double> costs = new ArrayList<>();
        List<Double> profits = new ArrayList<>();

        // Calculate total revenue, cost, and profit, and add data to chart lists
        for (Product product : products) {
            double revenue = product.getPrice() * product.getSales();
            double cost = product.getCost() * product.getSales();
            double profit = revenue - cost;

            totalRevenue += revenue;
            totalCost += cost;
            totalProfit += profit;

            productNames.add(product.getName());
            revenues.add(revenue);
            costs.add(cost);
            profits.add(profit);
        }

        // Create bar chart for revenue, cost, and profit
        CategoryChart chart = new CategoryChartBuilder()
            .width(800)
            .height(600)
            .title("Profit/Loss Report")
            .xAxisTitle("Product")
            .yAxisTitle("Amount")
            .theme(Styler.ChartTheme.Matlab)
            .build();

        chart.addSeries("Revenue", productNames, revenues)
            .setMarker(SeriesMarkers.NONE)
            .setLineColor(XChartSeriesColors.BLUE);
        chart.addSeries("Cost", productNames, costs)
            .setMarker(SeriesMarkers.NONE)
            .setLineColor(XChartSeriesColors.RED);
        chart.addSeries("Profit", productNames, profits)
            .setMarker(SeriesMarkers.NONE)
            .setLineColor(XChartSeriesColors.GREEN);

        new SwingWrapper<>(chart).displayChart();

        // Print total revenue, cost, and profit
        System.out.println("--------------------------------------------------");
        System.out.printf("Total Revenue: $%.2f%n", totalRevenue);
        System.out.printf("Total Cost: $%.2f%n", totalCost);
        System.out.printf("Total Profit: $%.2f%n", totalProfit);
    }
}
